name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - dev

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: collection-api

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test_unix:
    runs-on: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
            gradlew build
  test_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
            gradlew.bat build
