name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - dev

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: collection-api

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test_unix:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest, windows-latest]
        java-version: [8, 11]
    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java-version }} # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'

      - name: Run tests
        run: |
              if [ "$RUNNER_OS" == "Windows" ]; then
                ./gradlew.bat build
              else
                ./gradlew build
              fi
